version = 0.1
[default.global.parameters]
region = "ap-south-1"

[default.deploy.parameters]
no_confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[dev.deploy.parameters]
stack_name = "expense-tracker-dev"
s3_bucket = "temp-deployment-artifacts"
s3_prefix = "expense-tracker-artifacts"
tags = "Developer=\"gopalk\" Application=\"expense-tracker-backend-dev\" Environment=\"Dev\""

[stage.deploy.parameters]
stack_name = "expense-tracker-stage"
s3_bucket = "deploy-expense-tracker"
s3_prefix = "expense-tracker-stage-artifacts"
tags = "Developer=\"gopalk\" Application=\"expense-tracker-backend-stage\" Environment=\"Stage\""

[prod.deploy.parameters]
stack_name = "expense-tracker-prod"
s3_bucket = "deploy-expense-tracker"
s3_prefix = "expense-tracker-prod-artifacts"
tags = "Developer=\"gopalk\" Application=\"expense-tracker-backend-prod\" Environment=\"Prod\""