AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-tracker-backend

Parameters:
  DBSTRING:
    Description: "Required. The Database hostname or URL"
    Type: "String"
    Default: "mongodb+srv://<host>:<password>@expense-tracker.yvyiz.mongodb.net/expense-tracker?retryWrites=true&w=majority"
  DBUSER:
    Description: "Required. Db user"
    Type: "String"
    Default: "gopalk"
  DBPASSWORD:
    Description: "Required. Db password"
    Type: "String"
    Default: "Gopal%40T2910"
  DEPLOYMENT:
    Description: "Environment name - dev, test, stage, preprod, prod etc."
    Type: "String"
    Default: "envDeployment"
  AWSREGIONNAME:
    Description: "Required. S3 AWS Region"
    Type: "String"
    Default: "ap-south-1"
  
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
    GatewayResponses:
      DEFAULT_4xx:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
            Access-Control-Allow-Headers: "'*'"
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Credentials: "'*'"
      DEFAULT_5xx:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
            Access-Control-Allow-Headers: "'*'"
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Credentials: "'*'"
  Function:
    Environment:
      Variables:
        DB_STRING: !Ref DBSTRING
        DB_USER: !Ref DBUSER
        DB_PASSWORD: !Ref DBPASSWORD
        DEPLOYMENT: !Ref DEPLOYMENT
        AWS_REGION_NAME: !Ref AWSREGIONNAME
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 60

Resources:
  # lambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  #       - arn:aws:iam::aws:policy/SecretsManagerReadWrite
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
  #       - arn:aws:iam::aws:policy/AWSLambdaExecute
  #       - arn:aws:iam::aws:policy/AmazonS3FullAccess
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - lambda.amazonaws.com
  #           Action:
  #             - sts:AssumeRole

  CommonCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: expense-tracker-common-code-1
      Description: Code shared across all lambda functions
      ContentUri: src/common/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/hello
      Handler: hello.lambdaHandler
      # Role: !GetAtt lambdaExecutionRole.Arn
      Description: Hello function lambda
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - !Ref CommonCodeLayer
    Metadata:
      BuildMethod: nodejs14.x

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/createUser
      Handler: createUser.lambdaHandler
      # Role: !GetAtt lambdaExecutionRole.Arn
      Description: A lambda to create a new user
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /createUser
            Method: post
      Layers:
        - !Ref CommonCodeLayer
    Metadata:
      BuildMethod: nodejs14.x

